```css
Bellow is a list of all available commands.
```
```css
#register     

.wallet register -> Registers a new wallet for the user. You need to specify a valid CCX address.

Example: .wallet register <ccxAddress>
```
```css
#update     

.wallet update -> Updates the current user wallet with new CCX address.

Example: .wallet update <ccxAddress>
```
```css
#show     

.wallet show -> Gives the current wallet details for the user to DM.

Example: .wallet show
```
```css
#deposit     

.wallet deposit -> Give the user info about how to deposit to his/her wallet in a DM.

Example: .wallet deposit
```
```css
#balance     

.wallet balance -> Shows the current user wallet balance in a DM.

Example: .wallet balance
```
```css
#paymentid     

.wallet paymentid -> Generates a paymentId. This is for general purposes only.

Example: .wallet paymentid
```