```css

  #pools
    .pools help -> Gives detailed info on pools commands.
    .pools list -> Gives the list of all CCX pools.
    .pools info -> Gives the info about all CCX pools.
```
```css

  #wallet
    .wallet help -> Gives detailed info on wallet commands.
    .wallet register -> Registers a new wallet for the user. You need to specify a valid CCX address.
    .wallet update -> Updates the current user wallet with new CCX address.
    .wallet show -> Gives the current wallet details for the user.
    .wallet deposit -> Gives the user info about how to deposit to his/her wallet.
    .wallet withdraw -> Allows you to withdraw your funds back to your wallet.
    .wallet balance -> Shows the current user wallet balance.
    .wallet paymentid -> Generates a paymentId.
```
```css

  #rain
    .rain help -> Gives detailed info on rain commands.
    .rain recent -> Rains upon the users that were active recently.
    .rain alltime -> Rains upon the all time most active users.
    .rain period -> Rains upon the users that are most active in the last period.
    .rain random -> Rains upon the selected number of random users.
    .rain channel -> Rains upon users of selected channel.
    .rain role -> Rains upon users of selected role.
    .rain reset -> Resets the period counters.
    .rain beer -> Rains some beer for hot days.
```