```css
CCX Discord Bot

  #Markets:
    info        .info -> gives general info about the markets.
  
  #exchanges:
    info        .info -> gives general info about the exchanges.

  #blockchain:
    supply      .supply -> gives the current total supply of CCX.
    height      .height -> gives the current blockchain height.

  #wallet:
    register    .register -> registers a new wallet for the user. You need to specify a valid CCX address.
    update      .update -> updates the current user wallet with new CCX address.
    show        .show -> gives the current wallet details for the user.
    deposit     .deposit -> give the user info about how to deposit to his/her wallet
    balance     .balance -> shows the current user wallet balance
    paymentid   .paymentid -> generates a paymentId
    tip         .tip -> tip a user that also has a registered wallet
```