```css

  #wallet
    help         .wallet help -> gives detailed info on wallet commands.
    register     .wallet register -> registers a new wallet for the user. You need to specify a valid CCX address.
    update       .wallet update -> updates the current user wallet with new CCX address.
    show         .wallet show -> gives the current wallet details for the user.
    deposit      .wallet deposit -> give the user info about how to deposit to his/her wallet
    balance      .wallet balance -> shows the current user wallet balance
    paymentid    .wallet paymentid -> generates a paymentId
```
