```css
Below is a list of all available commands.
```
```css
#supply

.blockchain supply -> Gives the current circulating supply of CCX.

Example: .blockchain supply
```
```css
#height

.blockchain height -> Gives the current blockchain height.

Example: .blockchain height
```
```css
#reward

.blockchain reward -> Gives the current block reward.

Example: .blockchain reward
```
```css
#hashrate

.blockchain hashrate -> Gives the current hashrate of the network.

Example: .blockchain hashrate
```
```css
#totalsupply

.blockchain totalsupply -> Gives the current total supply.

Example: .blockchain totalsupply
```
```css
#maxsupply

.blockchain maxsupply -> Gives the max supply of CCX.

Example: .blockchain maxsupply
```
```css
#difficulty

.blockchain difficulty -> Gives the current difficulty of the network.

Example: .blockchain difficulty
```
