```css
CCX Discord Bot

The bot is organized into sections. So when you issue a command you need to use .<section> <command> to acces it.
For instance if you want to get the blockchain height you should call

.blockchain height

Bellow is a list of all available commands.
```
```css

  #markets
    help        .markets help -> gives detailed info on markets commands.
    info        .markets info -> gives general info about the markets.
    pricechart  .markets pricechart -> gives CCX price chart for last 7 days.
```
```css

  #exchanges
    help   .exchanges help -> gives detailed info on exchanges commands.
    info   .exchanges info -> gives general info about the exchanges.
```
```css

  #blockchain
    help         .blockchain help -> gives detailed info on blockchain commands.
    supply       .blockchain supply -> gives the current circulating supply of CCX.
    height       .blockchain height -> gives the current blockchain height.
    reward       .blockchain reward -> gives the current block reward.
    hashrate     .blockchain hashrate -> gives the current hashrate of the network.
    totalsupply  .blockchain totalsupply -> gives the current total supply.
    maxsupply    .blockchain maxsupply -> gives the max supply of CCX.
    difficulty   .blockchain difficulty -> gives the current difficulty of the network.
```
```css

  #giveaway
    help         .giveaway help -> gives detailed info on giveaway commands.
    create       .giveaway create -> creates a new giveaway based on parameters.
    list         .giveaway list -> lists all active giveaways.
    delete       .giveaway delete -> deletes an active giveaway.
```

