```css
CCX Discord Bot

The bot is organized into sections. So when you issue a command you need to use .<section> <command> to acces it.
For instance if you want to get the blockchain height you should call

.blockchain height

Bellow is a list of all available commands.
```
```css

  #markets
    .markets help -> gives detailed info on markets commands.
    .markets info -> gives general info about the markets.
    .markets pricechart -> gives CCX price chart for last 7 days.
```
```css

  #exchanges
    .exchanges help -> gives detailed info on exchanges commands.
    .exchanges info -> gives general info about the exchanges.
```
```css

  #blockchain
    .blockchain help -> gives detailed info on blockchain commands.
    .blockchain supply -> gives the current circulating supply of CCX.
    .blockchain height -> gives the current blockchain height.
    .blockchain reward -> gives the current block reward.
    .blockchain hashrate -> gives the current hashrate of the network.
    .blockchain totalsupply -> gives the current total supply.
    .blockchain maxsupply -> gives the max supply of CCX.
    .blockchain difficulty -> gives the current difficulty of the network.
```
```css

  #giveaway
    .giveaway help -> gives detailed info on giveaway commands.
    .giveaway create -> creates a new giveaway based on parameters.
    .giveaway list -> lists all active giveaways.
    .giveaway delete -> deletes an active giveaway.
```

