```css
CCX Discord Bot

  #Markets:
    info         .markets info -> gives general info about the markets.
  
  #exchanges:
    info         .exchanges info -> gives general info about the exchanges.

  #blockchain:
    supply       .blockchain supply -> gives the current circulating supply of CCX.
    height       .blockchain height -> gives the current blockchain height.
    reward       .blockchain reward -> gives the current block reward.
    hashrate     .blockchain hashrate -> gives the current hashrate of the network.
    totalsupply  .blockchain totalsupply -> gives the current total supply.
    maxsupply    .blockchain maxsupply -> gives the max supply of CCX.
    difficulty   .blockchain difficulty -> gives the current difficulty of the network.

  #wallet:
    register     .register -> registers a new wallet for the user. You need to specify a valid CCX address.
    update       .update -> updates the current user wallet with new CCX address.
    show         .show -> gives the current wallet details for the user.
    deposit      .deposit -> give the user info about how to deposit to his/her wallet
    balance      .balance -> shows the current user wallet balance
    paymentid    .paymentid -> generates a paymentId
    tip          .tip -> tip a user that also has a registered wallet
```