```css

  #pools
    help   .pools help -> gives detailed info on pools commands.
    list   .pools list -> gives the list of all CCX pools.
    info   .pools info -> gives the info about all CCX pools.
```
```css

  #wallet
    help         .wallet help -> gives detailed info on wallet commands.
    register     .wallet register -> registers a new wallet for the user. You need to specify a valid CCX address.
    update       .wallet update -> updates the current user wallet with new CCX address.
    show         .wallet show -> gives the current wallet details for the user.
    deposit      .wallet deposit -> give the user info about how to deposit to his/her wallet
    balance      .wallet balance -> shows the current user wallet balance
    paymentid    .wallet paymentid -> generates a paymentId
```
```css

  #general
    help         .help -> shows you this help content.
    tip          .tip -> tip a user that also has a registered wallet.
    say          .say -> makes the bot say something as if he said it.
    ban          .ban -> bans a user from the server.
    kick         .kick -> kicks a user from the server.
    purge        .purge -> purges last N messages from the channel. 
```
