```css

  #users
    .users help -> Gives detailed info on users commands.
    .users all -> Counts all users on the server.
    .users online -> Counts all online users on the server.
    .users offline -> Counts all offline users on the server.
    .users ban -> Bans a user from the server.
    .users kick -> Kicks a user from the server.
    .users list alltime|period|tippers -> List top 10 users by the specified criteria.
```
```css

  #general
    .help -> Shows you this help content.
    .tip -> Tip a user that also has a registered wallet.
    .say -> Makes the bot say something as if he said it.
    .purge -> Purges last N messages from the channel. 
```
