```css

  #blockchain
    help         .blockchain help -> gives detailed info on blockchain commands.
    supply       .blockchain supply -> gives the current circulating supply of CCX.
    height       .blockchain height -> gives the current blockchain height.
    reward       .blockchain reward -> gives the current block reward.
    hashrate     .blockchain hashrate -> gives the current hashrate of the network.
    totalsupply  .blockchain totalsupply -> gives the current total supply.
    maxsupply    .blockchain maxsupply -> gives the max supply of CCX.
    difficulty   .blockchain difficulty -> gives the current difficulty of the network.
```