```css
CCX Discord Bot

The bot is organized into sections. When you issue a command you need to use .<section> <command> to access it.
For instance, if you want to get the blockchain height you should call:

.blockchain height

Below is a list of all available commands.
```
```css

  #markets
    .markets help -> Detailed info on markets commands.
    .markets info -> General info about the markets.
    .markets pricechart -> CCX price chart for last 7 days.
```
```css

  #exchanges
    .exchanges help -> Detailed info on exchanges commands.
    .exchanges info -> General info about the exchanges.
```
```css

  #social
    .social help -> Detailed info on social commands.
    .social latest -> Latest tweets from Conceal Network.
    .social tweet <id> -> URL for a specific tweet.
```
```css

  #links
    .links help -> Detailed info on links commands.
    .links -> All available links.
    .links <name> -> Specific link.
```
```css

  #blockchain
    .blockchain help -> Detailed info on blockchain commands.
    .blockchain supply -> Current circulating supply of CCX.
    .blockchain height -> Current blockchain height.
    .blockchain reward -> Current block reward.
    .blockchain hashrate -> Current network hashrate.
    .blockchain totalsupply -> Current total supply.
    .blockchain maxsupply -> Max supply of CCX.
    .blockchain difficulty -> Current network difficulty.
    .blockchain nodecount -> Current node count.
    .blockchain smartnodecount -> Current smart node count.
```
```css

  #giveaway
    .giveaway help -> Detailed info on giveaway commands.
    .giveaway create -> Creates a new giveaway.
    .giveaway list -> Lists all active giveaways.
    .giveaway delete -> Deletes an active giveaway.
```
```css

  #settings
    .settings help -> Detailed info on settings commands.
    .settings mute -> Mutes or unmutes user events.
```

