```css
Below is a list of all available commands.
```
```css
#all

.users all -> Counts all users on the server.

Example: .users all
```
```css
#online

.users online -> Counts all online users on the server.

Example: .users online
```
```css
#offline

.users offline -> Counts all offline users on the server.

Example: .users offline
```
```css
#kick

.users kick -> Kicks all the mentioned user from the server. You need moderator or admin permissions for that.

Example: .users kick <user>
```
```css
#ban

.users ban -> Bans all the mentioned user from the server. You need moderator or admin permissions for that.

Example: .users ban <user>
```
