**Hey, {{this.username}}! Welcome to the Conceal Discord! :)**

If you're new here need support, head over to the  **#support** channel and post your problem there. Team will help you.
You can also head over to the **#annoucements** channel and see the latest news on where we are and what we are doing.
If you have questions or just want info, look for one the admins or devs currently online.

You can also use this bot to get more information.
Use the command `.help` to get list of commands.
Bot has a lot of command available in multiple sections. 
Docs are at: https://github.com/ConcealNetwork/conceal-xbot

Don't forget to register your wallet address with the bot with the command `.wallet register` so you can recieve tips
If you want to send tips then type `.wallet deposit` after you register your wallet address and transfer some funds to your TipJar

Where you can get info about Conceal:

* **Website:** https://conceal.network
* **Wiki:** https://conceal.network/wiki/doku.php
* **Wallets:** https://conceal.network/#wallets
* **Telegram:** https://t.co/55klBHKGUR
* **Twitter:** https://twitter.com/ConcealNetwork
* **Articles:** https://medium.com/@ConcealNetwork
* **Facebook:** https://www.facebook.com/concealnetwork
* **Github:** https://github.com/ConcealNetwork
