**Hey, {{this.member.name}}! Welcome to the Conceal Discord! :)**

If you're new here and have some questions head over to the  **#faq** channel for an introduction to the project and answers to common questions.
You can also head over to the **#annoucements##** channel and see the latest news on where we are and what we are doing.
If you have more questions, look for one the admins or devs

**Devs currently online:**

You can also use this bot to get more information.
Use the command `.help` to get list of commands.
You can also see current network information with `.stats` or other specific commands like `.hashrate`, `.height`, `.difficulty`, and `.supply'
Don't forget to register your wallet address with the bot with the command `.registerwallet` so you can recieve tips
If you want to send tips then type `.deposit` after you register your wallet address and transfer some funds to your TipJar
